Spring boot online book store add jwt
snowfallen/spring-boot-online-book-store pull request #12
Opened 2024-06-15 18:01 UTC by snowfallen

2024-06-16 13:17 UTC, okuzan requested changes

2024-06-16 13:17 UTC, okuzan commented on src/main/java/book/store/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
make Bearer a constant, or import existing one, Spring should have it, then 7 would be .length of it - they are logically connected, and good code should make it obvious :)

2024-06-17 05:55 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-06-17 05:55 UTC, Elena-Bruyako commented on src/main/java/book/store/security/JwtAuthenticationFilter.java
> +        String bearerToken = httpServletRequest.getHeader("Authorization");
Use Spring constant HttpHeaders.AUTHORIZATION

2024-06-17 05:55 UTC, Elena-Bruyako commented on src/main/java/book/store/security/JwtAuthenticationFilter.java
> +    private static final String TOKEN_PREFIX = "Bearer";
```suggestion
    private static final String TOKEN_PREFIX = "Bearer ";
```

2024-06-17 05:55 UTC, Elena-Bruyako commented on src/main/java/book/store/config/SecurityConfig.java
> -                                .requestMatchers("/auth/**", "/swagger-ui/**", "/v3/api-docs/**")
Why did you decide to remove "/swagger-ui/**", "/v3/api-docs/**" ?

2024-06-17 16:23 UTC, Vasul-Pankiv approved these changes

2024-06-17 19:34 UTC, merged