Spring boot online book store add shopping card
snowfallen/spring-boot-online-book-store pull request #14
Opened 2024-10-31 11:21 UTC by snowfallen

2024-10-31 13:24 UTC, Elena-Bruyako requested changes
see comments

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/controller/ShoppingCartController.java
> +    public CartItemResponseDto addCartItem(
```suggestion
    public ShoppingCartResponseDto addCartItem(
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/controller/ShoppingCartController.java
> +    public CartItemResponseDto updateCartItemBy(
```suggestion
    public ShoppingCartResponseDto updateCartItemBy(
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/controller/ShoppingCartController.java
> +    public CartItemResponseDto deleteCartItemById(@PathVariable Long id) {
```suggestion
    public void deleteCartItemById(@PathVariable Long id) {
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/dto/cart/item/CartItemRequestDto.java
> +        @Positive
```suggestion
        @Positive
        @NotNull
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/model/CartItem.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY, optional = false)
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/model/CartItem.java
> +    @Column(name = "quantity", nullable = false)
```suggestion
    @Column(nullable = false)
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/model/ShoppingCart.java
> +    @Column(name = "is_deleted", nullable = false, columnDefinition = "TINYINT")
```suggestion
    @Column(nullable = false, columnDefinition = "TINYINT")
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/model/ShoppingCart.java
> +    @OneToOne
minor comment
you can use `@MapsId` here

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/repository/cart/item/CartItemRepository.java
> +    Set<CartItem> findCartItemsByShoppingCartId(@Param("shoppingCartId") Long shoppingCart);
```suggestion
    Optional<CartItem> findByIdAndShoppingCartId(Long itemId, Long cartId);
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/repository/shopping/cart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findWithCartItemsById(Long id);
```suggestion
    @EntityGraph(attributePaths = {"cartItems", "cartItems.book"})
    ShoppingCart findByUserId(Long userId);
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/service/cart/item/impl/CartItemServiceImpl.java
> +public class CartItemServiceImpl implements CartItemService {
remove this service, all logic should be in ShopCartService

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +
```suggestion
        shoppingCartRepository.save(shoppingCart);
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +    public CartItemResponseDto addCartItem(CartItemRequestDto requestDto,
```suggestion
    public ShoppingCartResponseDto addCartItem(CartItemRequestDto requestDto,
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +        User authenticatedUser = (User) authentication.getPrincipal();
create separate method to get Long user id from authentication

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +        );
```suggestion
        return shoppingCartMapper.toDto(shoppingCartRepository.findByUserId(userId));
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = getShoppingCart((User) authentication.getPrincipal());
the logic should be 
find book
find shop cart
check if shop cart includes this book, if yes - increase quantity
if no - add cartItem to shop cart

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/java/book/store/service/user/impl/UserServiceImpl.java
> +
```suggestion
        shoppingCartService.createShoppingCart(user);
```

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/14-fill-shopping-cart-with-data.yaml
> +      id: fill-shopping-cart-with-data
remove this changeset

2024-10-31 13:24 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/16-fill-cart-items-table-with-data.yaml
> +      id: fill-cart-items-table-with-data
remove this changeset

2024-11-02 18:55 UTC, Elena-Bruyako requested changes
see comments

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/controller/ShoppingCartController.java
> +    public ShoppingCartResponseDto addCartItem(
add to every endpoint
```suggestion
    public ShoppingCartResponseDto addCartItem(Authentication authentication,
```

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/dto/cart/item/CartItemRequestDto.java
> +        @NotNull
int can't be null
```suggestion
```

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/dto/cart/item/CartItemUpdateQuantityDto.java
> +        @NotNull
same here

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/service/user/impl/UserServiceImpl.java
> +        User savedUser = userRepository.save(user);
```suggestion
        userRepository.save(user);
```

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/service/user/impl/UserServiceImpl.java
> +        eventPublisher.publishEvent(new UserRegisteredEvent(this, savedUser));
interesting approach, it's good that you try to implement it. 
Not sure if you should use this approach for this simple functionality, so you can just add `createShoppingCart(user)` to shopCartService

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart", orphanRemoval = true)
add Cascade type All

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/model/ShoppingCart.java
> +    @OneToOne(fetch = FetchType.LAZY, optional = false)
you can use `@MapsId` here

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/repository/cart/item/CartItemRepository.java
> +    Set<CartItem> findCartItemsByShoppingCartId(@Param("shoppingCartId") Long shoppingCart);
not fixed

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/service/book/BookService.java
> +    Book getBookById(Long id);
remove

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/service/book/impl/BookServiceImpl.java
> +    public Book getBookById(Long id) {
```suggestion
    private Book getBookById(Long id) {
```

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +        shoppingCart.setCartItems(new HashSet<>());
```suggestion
```

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-11-02 18:55 UTC, Elena-Bruyako commented on src/main/java/book/store/service/user/UserService.java
> +    User getAuthUser();
remove

2025-03-25 14:46 UTC, snowfallen commented on src/main/java/book/store/service/user/impl/UserServiceImpl.java
> +        eventPublisher.publishEvent(new UserRegisteredEvent(this, savedUser));
In this case -  yes, but in the future, we might need to add new logic (like sending an email when a user is created or something similar)

2025-03-25 18:23 UTC, Elena-Bruyako requested changes

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/Application.java
> +@EnableAsync
```suggestion
```

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/event/user/UserRegisteredEvent.java
> +public class UserRegisteredEvent extends ApplicationEvent {
What purpose of this class?

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/listener/user/UserRegistrationListener.java
> +public class UserRegistrationListener {
remove

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/listener/user/UserRegistrationListener.java
> +public class UserRegistrationListener {
Why do you add additional logic to existing PR and HW?

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/model/ShoppingCart.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
```

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/model/ShoppingCart.java
> +@Where(clause = "is_deleted = false")
`@Where` is deprecated

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/model/ShoppingCart.java
> +    @OneToOne(fetch = FetchType.LAZY, optional = false)
```suggestion
    @MapsId
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id", nullable = false)
```

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/service/book/BookService.java
> +    Book getBookById(Long id);
remove

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/service/book/impl/BookServiceImpl.java
> +    public Book getBookById(Long id) {
```suggestion
    private Book getBookById(Long id) {
```

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/ShoppingCartService.java
> +    void delete(Long id, Authentication authentication);
```suggestion
    ShoppingCartResponseDto addCartItem(CartItemRequestDto requestDto,
                                        Long userId);

    ShoppingCartResponseDto get(Long userId);

    ShoppingCartResponseDto update(
            CartItemUpdateQuantityDto updateQuantityDto,
            Long id, Long userId);

    void delete(Long id, Long userId);
```

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +@Service
```suggestion
@Service
@Transactional
```

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
```

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = getCartItemForUser(id, authentication);
find shop cart by userId
find CartItem by `findByIdAndShoppingCartId`

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/service/shopping/cart/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItemForUser = getCartItemForUser(id, authentication);
same here

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/service/user/impl/UserServiceImpl.java
> +        User savedUser = userRepository.save(user);
```suggestion
        userRepository.save(user);
```

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/service/user/impl/UserServiceImpl.java
> +        eventPublisher.publishEvent(new UserRegisteredEvent(this, savedUser));
```suggestion
```

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/service/user/impl/UserServiceImpl.java
> +    private Set<Role> setDafaultRoleSet() throws RegistrationException {
remove

2025-03-25 18:23 UTC, Elena-Bruyako commented on src/main/java/book/store/service/user/impl/UserServiceImpl.java
> +        user.setRoles(setDafaultRoleSet());
```suggestion
        Role userRole = roleRepository.findRoleByName(Role.RoleName.ROLE_USER)
                .orElseThrow(() -> new RegistrationException(CANT_FIND_ROLE_BY_NAME)
                );
        user.setRoles(Set.of(userRole));
```

2025-03-26 18:02 UTC, Elena-Bruyako approved these changes

2025-03-27 08:57 UTC, merged